### ISSUE TITLE
What would be the best way to connect to the Dovecot instance like what are the default credentials?

### ISSUE THREAD

**Issue by Leopere** [jon6fingrs/mbsync#1]
Title explains it all.

**Comment by jon6fingrs** [comment]
> Title explains it all.
> 
> 

You don't necessarily connect them. You just chose the same path for Mail from both containers. Mbsync will populate it and dovecot will serve it. 

There isn't a default password for dovecot. It can be whatever you want.

**Comment by Leopere** [comment]
I guess I’m just looking for an answer as to what I would use to view these emails now that they’re in Dovecot I was planning on connecting my local copy of Webmail

**Comment by jon6fingrs** [comment]
So you set whatever you want the dovecot credentials to be and then you use those same credentials with whatever email client you use.
